database:
  host: warmhouse-postgres
  port: 5432
  user: warmhouse_user_api
  password: user_api_dev_pass_123
  db_name: warmhouse

rabbitmq:
    url: amqp://smarthome:rabbitmq_dev_pass_123@warmhouse-rabbitmq:5672/

jwt_secret: your_jwt_secret_key_here_make_it_long_and_secure
smarthome_api_key: smarthome_service_token_123
