version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: smarthome
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./smart_home/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - smarthome-network

  device-service:
    container_name: device-service
    build: 
        context: ./device
        dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/smarthome
      - TELEMETRY_SERVICE_URL=http://telemetry-service:8084
      - LAMP_SERVICE_URL=http://lamp-service:8083
      - TEMPERATURE_API_URL=http://temperature-api:8082
    depends_on:
      postgres:
        condition: service_started
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 10s
    networks:
      - smarthome-network

  telemetry-service:
    container_name: telemetry-service
    build: 
        context: ./telemetry
        dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/smarthome
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/health"]
      interval: 10s
    networks:
      - smarthome-network

  lamp-service:
    container_name: lamp-service
    build: 
        context: ./lamp
        dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - DEVICE_SERVICE_URL=http://device-service:8082
      - TELEMETRY_SERVICE_URL=http://telemetry-service:8084
    depends_on:
      device-service:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/health"]
      interval: 10s
    networks:
      - smarthome-network

  temperature-api:
    build: 
        context: ./temperature-api
        dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
    restart: unless-stopped
    networks:
      - smarthome-network

  app:
    build:
      context: ./smart_home
      dockerfile: Dockerfile
    container_name: smarthome-app
    depends_on:
      postgres:
        condition: service_healthy
      temperature-api:
        condition: service_started
      device-service:
        condition: service_started
      lamp-service:
        condition: service_started  
    environment:
      - DEVICE_SERVICE_URL=http://device-service:8082
      - LAMP_SERVICE_URL=http://lamp-service:8083
      - TELEMETRY_SERVICE_URL=http://telemetry-service:8084
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/smarthome
      - TEMPERATURE_API_URL=http://temperature-api:8081
    ports:
      - "8080:8080"
    restart: always
    networks:
      - smarthome-network

volumes:
  postgres_data:

networks:
  smarthome-network:
    driver: bridge